/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MediateService.h"

#include "MediateService.tcc"

namespace seqsvr {

} // seqsvr
namespace apache { namespace thrift {

}} // apache::thrift
