/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/ServiceIncludes.h>
#include <thrift/lib/cpp2/async/HeaderChannel.h>
#include <thrift/lib/cpp/TApplicationException.h>
#include <thrift/lib/cpp2/async/FutureRequest.h>
#include <folly/futures/Future.h>



#include "seqsvr_types.h"

namespace folly {
  class IOBuf;
  class IOBufQueue;
}
namespace apache { namespace thrift {
  class Cpp2RequestContext;
  class BinaryProtocolReader;
  class CompactProtocolReader;
  namespace transport { class THeader; }
}}

namespace seqsvr {

class MediateServiceSvAsyncIf {
 public:
  virtual ~MediateServiceSvAsyncIf() {}
  virtual void async_tm_RegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = 0;
  // virtual void async_RegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = delete;
  virtual folly::Future<folly::Unit> future_RegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = 0;
  virtual void async_tm_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = 0;
  // virtual void async_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = delete;
  virtual folly::Future<folly::Unit> future_UnRegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) = 0;
};

class MediateServiceAsyncProcessor;

class MediateServiceSvIf : public MediateServiceSvAsyncIf, public apache::thrift::ServerInterface {
 public:
  typedef MediateServiceAsyncProcessor ProcessorType;
  std::unique_ptr<apache::thrift::AsyncProcessor> getProcessor() override;
  virtual void RegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> /*node_addr*/);
  folly::Future<folly::Unit> future_RegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) override;
  void async_tm_RegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) override;
  virtual void UnRegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> /*node_addr*/);
  folly::Future<folly::Unit> future_UnRegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) override;
  void async_tm_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::HandlerCallback<void>> callback, std::unique_ptr< ::seqsvr::NodeAddrInfo> node_addr) override;
};

class MediateServiceSvNull : public MediateServiceSvIf {
 public:
  void RegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> /*node_addr*/) override;
  void UnRegisterAllocSvr(std::unique_ptr< ::seqsvr::NodeAddrInfo> /*node_addr*/) override;
};

class MediateServiceAsyncProcessor : public ::apache::thrift::GeneratedAsyncProcessor {
 public:
  const char* getServiceName() override;
  using BaseAsyncProcessor = void;
  using HasFrozen2 = std::false_type;
 protected:
  MediateServiceSvIf* iface_;
  folly::Optional<std::string> getCacheKey(folly::IOBuf* buf, apache::thrift::protocol::PROTOCOL_TYPES protType) override;
 public:
  void process(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, apache::thrift::protocol::PROTOCOL_TYPES protType, apache::thrift::Cpp2RequestContext* context, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm) override;
 protected:
  bool isOnewayMethod(const folly::IOBuf* buf, const apache::thrift::transport::THeader* header) override;
 private:
  static std::unordered_set<std::string> onewayMethods_;
  static std::unordered_map<std::string, int16_t> cacheKeyMap_;
 public:
  using BinaryProtocolProcessFunc = ProcessFunc<MediateServiceAsyncProcessor, apache::thrift::BinaryProtocolReader>;
  using BinaryProtocolProcessMap = ProcessMap<BinaryProtocolProcessFunc>;
  static const MediateServiceAsyncProcessor::BinaryProtocolProcessMap& getBinaryProtocolProcessMap();
 private:
  static const MediateServiceAsyncProcessor::BinaryProtocolProcessMap binaryProcessMap_;
 public:
  using CompactProtocolProcessFunc = ProcessFunc<MediateServiceAsyncProcessor, apache::thrift::CompactProtocolReader>;
  using CompactProtocolProcessMap = ProcessMap<CompactProtocolProcessFunc>;
  static const MediateServiceAsyncProcessor::CompactProtocolProcessMap& getCompactProtocolProcessMap();
 private:
  static const MediateServiceAsyncProcessor::CompactProtocolProcessMap compactProcessMap_;
 private:
  template <typename ProtocolIn_, typename ProtocolOut_>
  void _processInThread_RegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void process_RegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <class ProtocolIn_, class ProtocolOut_>
  static folly::IOBufQueue return_RegisterAllocSvr(int32_t protoSeqId, apache::thrift::ContextStack* ctx);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_RegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void _processInThread_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot, apache::thrift::Cpp2RequestContext* ctx, folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <typename ProtocolIn_, typename ProtocolOut_>
  void process_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req, std::unique_ptr<folly::IOBuf> buf, std::unique_ptr<ProtocolIn_> iprot,apache::thrift::Cpp2RequestContext* ctx,folly::EventBase* eb, apache::thrift::concurrency::ThreadManager* tm);
  template <class ProtocolIn_, class ProtocolOut_>
  static folly::IOBufQueue return_UnRegisterAllocSvr(int32_t protoSeqId, apache::thrift::ContextStack* ctx);
  template <class ProtocolIn_, class ProtocolOut_>
  static void throw_wrapped_UnRegisterAllocSvr(std::unique_ptr<apache::thrift::ResponseChannel::Request> req,int32_t protoSeqId,apache::thrift::ContextStack* ctx,folly::exception_wrapper ew,apache::thrift::Cpp2RequestContext* reqCtx);
 public:
  MediateServiceAsyncProcessor(MediateServiceSvIf* iface) :
      iface_(iface) {}

  virtual ~MediateServiceAsyncProcessor() {}
};

class MediateServiceAsyncClient : public apache::thrift::TClientBase {
 public:
  virtual const char* getServiceName();
  typedef std::unique_ptr<apache::thrift::RequestChannel, folly::DelayedDestruction::Destructor> channel_ptr;

  virtual ~MediateServiceAsyncClient() {}

  MediateServiceAsyncClient(std::shared_ptr<apache::thrift::RequestChannel> channel) :
      channel_(channel) {
    connectionContext_.reset(new apache::thrift::Cpp2ConnContext);
  }

  apache::thrift::RequestChannel*  getChannel() {
    return this->channel_.get();
  }

  apache::thrift::HeaderChannel*  getHeaderChannel() {
    return dynamic_cast<apache::thrift::HeaderChannel*>(this->channel_.get());
  }
  virtual void RegisterAllocSvr(std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void RegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
 private:
  virtual void RegisterAllocSvrImpl(bool useSync, apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
 public:
  virtual void sync_RegisterAllocSvr(const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void sync_RegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<folly::Unit> future_RegisterAllocSvr(const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<folly::Unit> future_RegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_future_RegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void RegisterAllocSvr(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  static folly::exception_wrapper recv_wrapped_RegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  static void recv_RegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  virtual void recv_instance_RegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  virtual folly::exception_wrapper recv_instance_wrapped_RegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  template <typename Protocol_>
  void RegisterAllocSvrT(Protocol_* prot, bool useSync, apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  template <typename Protocol_>
  static folly::exception_wrapper recv_wrapped_RegisterAllocSvrT(Protocol_* prot, ::apache::thrift::ClientReceiveState& state);
  template <typename Protocol_>
  static void recv_RegisterAllocSvrT(Protocol_* prot, ::apache::thrift::ClientReceiveState& state);
  virtual void UnRegisterAllocSvr(std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void UnRegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
 private:
  virtual void UnRegisterAllocSvrImpl(bool useSync, apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
 public:
  virtual void sync_UnRegisterAllocSvr(const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void sync_UnRegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<folly::Unit> future_UnRegisterAllocSvr(const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<folly::Unit> future_UnRegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual folly::Future<std::pair<folly::Unit, std::unique_ptr<apache::thrift::transport::THeader>>> header_future_UnRegisterAllocSvr(apache::thrift::RpcOptions& rpcOptions, const  ::seqsvr::NodeAddrInfo& node_addr);
  virtual void UnRegisterAllocSvr(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  static folly::exception_wrapper recv_wrapped_UnRegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  static void recv_UnRegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  virtual void recv_instance_UnRegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  virtual folly::exception_wrapper recv_instance_wrapped_UnRegisterAllocSvr(::apache::thrift::ClientReceiveState& state);
  template <typename Protocol_>
  void UnRegisterAllocSvrT(Protocol_* prot, bool useSync, apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::seqsvr::NodeAddrInfo& node_addr);
  template <typename Protocol_>
  static folly::exception_wrapper recv_wrapped_UnRegisterAllocSvrT(Protocol_* prot, ::apache::thrift::ClientReceiveState& state);
  template <typename Protocol_>
  static void recv_UnRegisterAllocSvrT(Protocol_* prot, ::apache::thrift::ClientReceiveState& state);
 protected:
  std::unique_ptr<apache::thrift::Cpp2ConnContext> connectionContext_;
  std::shared_ptr<apache::thrift::RequestChannel> channel_;
};

} // seqsvr
namespace apache { namespace thrift {

}} // apache::thrift
