/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "seqsvr_constants.h"

#include <folly/Indestructible.h>

namespace seqsvr {

} // seqsvr
