/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "StoreService.h"

#include "StoreService.tcc"

namespace seqsvr {

} // seqsvr
namespace apache { namespace thrift {

}} // apache::thrift
