// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seqsvr.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "seqsvr.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* FetchNextSequenceReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FetchNextSequenceReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetCurrentSequenceReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetCurrentSequenceReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SequenceRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SequenceRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* FetchNextSequenceListReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FetchNextSequenceListReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetCurrentSequenceListReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetCurrentSequenceListReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* IdSeq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IdSeq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SequenceListRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SequenceListRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoadMaxSeqsDataReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoadMaxSeqsDataReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoadMaxSeqsDataRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoadMaxSeqsDataRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* SaveMaxSeqReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SaveMaxSeqReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SaveMaxSeqRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SaveMaxSeqRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_seqsvr_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_seqsvr_2eproto() {
  protobuf_AddDesc_seqsvr_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "seqsvr.proto");
  GOOGLE_CHECK(file != NULL);
  FetchNextSequenceReq_descriptor_ = file->message_type(0);
  static const int FetchNextSequenceReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FetchNextSequenceReq, id_),
  };
  FetchNextSequenceReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FetchNextSequenceReq_descriptor_,
      FetchNextSequenceReq::internal_default_instance(),
      FetchNextSequenceReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(FetchNextSequenceReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FetchNextSequenceReq, _internal_metadata_));
  GetCurrentSequenceReq_descriptor_ = file->message_type(1);
  static const int GetCurrentSequenceReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetCurrentSequenceReq, id_),
  };
  GetCurrentSequenceReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetCurrentSequenceReq_descriptor_,
      GetCurrentSequenceReq::internal_default_instance(),
      GetCurrentSequenceReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetCurrentSequenceReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetCurrentSequenceReq, _internal_metadata_));
  SequenceRsp_descriptor_ = file->message_type(2);
  static const int SequenceRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SequenceRsp, sequence_),
  };
  SequenceRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SequenceRsp_descriptor_,
      SequenceRsp::internal_default_instance(),
      SequenceRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(SequenceRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SequenceRsp, _internal_metadata_));
  FetchNextSequenceListReq_descriptor_ = file->message_type(3);
  static const int FetchNextSequenceListReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FetchNextSequenceListReq, id_list_),
  };
  FetchNextSequenceListReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FetchNextSequenceListReq_descriptor_,
      FetchNextSequenceListReq::internal_default_instance(),
      FetchNextSequenceListReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(FetchNextSequenceListReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FetchNextSequenceListReq, _internal_metadata_));
  GetCurrentSequenceListReq_descriptor_ = file->message_type(4);
  static const int GetCurrentSequenceListReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetCurrentSequenceListReq, id_list_),
  };
  GetCurrentSequenceListReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetCurrentSequenceListReq_descriptor_,
      GetCurrentSequenceListReq::internal_default_instance(),
      GetCurrentSequenceListReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetCurrentSequenceListReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetCurrentSequenceListReq, _internal_metadata_));
  IdSeq_descriptor_ = file->message_type(5);
  static const int IdSeq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IdSeq, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IdSeq, sequence_),
  };
  IdSeq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      IdSeq_descriptor_,
      IdSeq::internal_default_instance(),
      IdSeq_offsets_,
      -1,
      -1,
      -1,
      sizeof(IdSeq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IdSeq, _internal_metadata_));
  SequenceListRsp_descriptor_ = file->message_type(6);
  static const int SequenceListRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SequenceListRsp, sequence_list_),
  };
  SequenceListRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SequenceListRsp_descriptor_,
      SequenceListRsp::internal_default_instance(),
      SequenceListRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(SequenceListRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SequenceListRsp, _internal_metadata_));
  LoadMaxSeqsDataReq_descriptor_ = file->message_type(7);
  static const int LoadMaxSeqsDataReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadMaxSeqsDataReq, set_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadMaxSeqsDataReq, alloc_id_),
  };
  LoadMaxSeqsDataReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoadMaxSeqsDataReq_descriptor_,
      LoadMaxSeqsDataReq::internal_default_instance(),
      LoadMaxSeqsDataReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoadMaxSeqsDataReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadMaxSeqsDataReq, _internal_metadata_));
  LoadMaxSeqsDataRsp_descriptor_ = file->message_type(8);
  static const int LoadMaxSeqsDataRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadMaxSeqsDataRsp, max_seqs_),
  };
  LoadMaxSeqsDataRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoadMaxSeqsDataRsp_descriptor_,
      LoadMaxSeqsDataRsp::internal_default_instance(),
      LoadMaxSeqsDataRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoadMaxSeqsDataRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadMaxSeqsDataRsp, _internal_metadata_));
  SaveMaxSeqReq_descriptor_ = file->message_type(9);
  static const int SaveMaxSeqReq_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqReq, set_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqReq, alloc_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqReq, section_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqReq, max_seq_),
  };
  SaveMaxSeqReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SaveMaxSeqReq_descriptor_,
      SaveMaxSeqReq::internal_default_instance(),
      SaveMaxSeqReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SaveMaxSeqReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqReq, _internal_metadata_));
  SaveMaxSeqRsp_descriptor_ = file->message_type(10);
  static const int SaveMaxSeqRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqRsp, last_max_seq_),
  };
  SaveMaxSeqRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SaveMaxSeqRsp_descriptor_,
      SaveMaxSeqRsp::internal_default_instance(),
      SaveMaxSeqRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(SaveMaxSeqRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SaveMaxSeqRsp, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_seqsvr_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FetchNextSequenceReq_descriptor_, FetchNextSequenceReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetCurrentSequenceReq_descriptor_, GetCurrentSequenceReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SequenceRsp_descriptor_, SequenceRsp::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FetchNextSequenceListReq_descriptor_, FetchNextSequenceListReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetCurrentSequenceListReq_descriptor_, GetCurrentSequenceListReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      IdSeq_descriptor_, IdSeq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SequenceListRsp_descriptor_, SequenceListRsp::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoadMaxSeqsDataReq_descriptor_, LoadMaxSeqsDataReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoadMaxSeqsDataRsp_descriptor_, LoadMaxSeqsDataRsp::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SaveMaxSeqReq_descriptor_, SaveMaxSeqReq::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SaveMaxSeqRsp_descriptor_, SaveMaxSeqRsp::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_seqsvr_2eproto() {
  FetchNextSequenceReq_default_instance_.Shutdown();
  delete FetchNextSequenceReq_reflection_;
  GetCurrentSequenceReq_default_instance_.Shutdown();
  delete GetCurrentSequenceReq_reflection_;
  SequenceRsp_default_instance_.Shutdown();
  delete SequenceRsp_reflection_;
  FetchNextSequenceListReq_default_instance_.Shutdown();
  delete FetchNextSequenceListReq_reflection_;
  GetCurrentSequenceListReq_default_instance_.Shutdown();
  delete GetCurrentSequenceListReq_reflection_;
  IdSeq_default_instance_.Shutdown();
  delete IdSeq_reflection_;
  SequenceListRsp_default_instance_.Shutdown();
  delete SequenceListRsp_reflection_;
  LoadMaxSeqsDataReq_default_instance_.Shutdown();
  delete LoadMaxSeqsDataReq_reflection_;
  LoadMaxSeqsDataRsp_default_instance_.Shutdown();
  delete LoadMaxSeqsDataRsp_reflection_;
  SaveMaxSeqReq_default_instance_.Shutdown();
  delete SaveMaxSeqReq_reflection_;
  SaveMaxSeqRsp_default_instance_.Shutdown();
  delete SaveMaxSeqRsp_reflection_;
}

void protobuf_InitDefaults_seqsvr_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  FetchNextSequenceReq_default_instance_.DefaultConstruct();
  GetCurrentSequenceReq_default_instance_.DefaultConstruct();
  SequenceRsp_default_instance_.DefaultConstruct();
  FetchNextSequenceListReq_default_instance_.DefaultConstruct();
  GetCurrentSequenceListReq_default_instance_.DefaultConstruct();
  IdSeq_default_instance_.DefaultConstruct();
  SequenceListRsp_default_instance_.DefaultConstruct();
  LoadMaxSeqsDataReq_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  LoadMaxSeqsDataRsp_default_instance_.DefaultConstruct();
  SaveMaxSeqReq_default_instance_.DefaultConstruct();
  SaveMaxSeqRsp_default_instance_.DefaultConstruct();
  FetchNextSequenceReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  GetCurrentSequenceReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  SequenceRsp_default_instance_.get_mutable()->InitAsDefaultInstance();
  FetchNextSequenceListReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  GetCurrentSequenceListReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  IdSeq_default_instance_.get_mutable()->InitAsDefaultInstance();
  SequenceListRsp_default_instance_.get_mutable()->InitAsDefaultInstance();
  LoadMaxSeqsDataReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  LoadMaxSeqsDataRsp_default_instance_.get_mutable()->InitAsDefaultInstance();
  SaveMaxSeqReq_default_instance_.get_mutable()->InitAsDefaultInstance();
  SaveMaxSeqRsp_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_seqsvr_2eproto_once_);
void protobuf_InitDefaults_seqsvr_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_seqsvr_2eproto_once_,
                 &protobuf_InitDefaults_seqsvr_2eproto_impl);
}
void protobuf_AddDesc_seqsvr_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_seqsvr_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014seqsvr.proto\022\006zproto\"\"\n\024FetchNextSeque"
    "nceReq\022\n\n\002id\030\001 \001(\r\"#\n\025GetCurrentSequence"
    "Req\022\n\n\002id\030\001 \001(\r\"\037\n\013SequenceRsp\022\020\n\010sequen"
    "ce\030\001 \001(\004\"+\n\030FetchNextSequenceListReq\022\017\n\007"
    "id_list\030\001 \003(\r\",\n\031GetCurrentSequenceListR"
    "eq\022\017\n\007id_list\030\001 \003(\r\"%\n\005IdSeq\022\n\n\002id\030\001 \001(\r"
    "\022\020\n\010sequence\030\002 \001(\004\"7\n\017SequenceListRsp\022$\n"
    "\rsequence_list\030\001 \003(\0132\r.zproto.IdSeq\"6\n\022L"
    "oadMaxSeqsDataReq\022\016\n\006set_id\030\001 \001(\r\022\020\n\010all"
    "oc_id\030\002 \001(\r\"&\n\022LoadMaxSeqsDataRsp\022\020\n\010max"
    "_seqs\030\001 \001(\014\"V\n\rSaveMaxSeqReq\022\016\n\006set_id\030\001"
    " \001(\r\022\020\n\010alloc_id\030\002 \001(\r\022\022\n\nsection_id\030\003 \001"
    "(\r\022\017\n\007max_seq\030\004 \001(\004\"%\n\rSaveMaxSeqRsp\022\024\n\014"
    "last_max_seq\030\001 \001(\004B#\n\027com.zchat.engine.z"
    "protoB\006ZProtoH\002b\006proto3", 583);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "seqsvr.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_seqsvr_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_seqsvr_2eproto_once_);
void protobuf_AddDesc_seqsvr_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_seqsvr_2eproto_once_,
                 &protobuf_AddDesc_seqsvr_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_seqsvr_2eproto {
  StaticDescriptorInitializer_seqsvr_2eproto() {
    protobuf_AddDesc_seqsvr_2eproto();
  }
} static_descriptor_initializer_seqsvr_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FetchNextSequenceReq::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FetchNextSequenceReq::FetchNextSequenceReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.FetchNextSequenceReq)
}

void FetchNextSequenceReq::InitAsDefaultInstance() {
}

FetchNextSequenceReq::FetchNextSequenceReq(const FetchNextSequenceReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.FetchNextSequenceReq)
}

void FetchNextSequenceReq::SharedCtor() {
  id_ = 0u;
  _cached_size_ = 0;
}

FetchNextSequenceReq::~FetchNextSequenceReq() {
  // @@protoc_insertion_point(destructor:zproto.FetchNextSequenceReq)
  SharedDtor();
}

void FetchNextSequenceReq::SharedDtor() {
}

void FetchNextSequenceReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FetchNextSequenceReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FetchNextSequenceReq_descriptor_;
}

const FetchNextSequenceReq& FetchNextSequenceReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<FetchNextSequenceReq> FetchNextSequenceReq_default_instance_;

FetchNextSequenceReq* FetchNextSequenceReq::New(::google::protobuf::Arena* arena) const {
  FetchNextSequenceReq* n = new FetchNextSequenceReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FetchNextSequenceReq::UnsafeMergeFrom(const FetchNextSequenceReq& from) {
  MergeFrom(from);
}
void FetchNextSequenceReq::Swap(FetchNextSequenceReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FetchNextSequenceReq::InternalSwap(FetchNextSequenceReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata FetchNextSequenceReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FetchNextSequenceReq_descriptor_;
  metadata.reflection = FetchNextSequenceReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FetchNextSequenceReq

// optional uint32 id = 1;
void FetchNextSequenceReq::clear_id() {
  id_ = 0u;
}
::google::protobuf::uint32 FetchNextSequenceReq::id() const {
  // @@protoc_insertion_point(field_get:zproto.FetchNextSequenceReq.id)
  return id_;
}
void FetchNextSequenceReq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.FetchNextSequenceReq.id)
}

inline const FetchNextSequenceReq* FetchNextSequenceReq::internal_default_instance() {
  return &FetchNextSequenceReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetCurrentSequenceReq::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetCurrentSequenceReq::GetCurrentSequenceReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetCurrentSequenceReq)
}

void GetCurrentSequenceReq::InitAsDefaultInstance() {
}

GetCurrentSequenceReq::GetCurrentSequenceReq(const GetCurrentSequenceReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetCurrentSequenceReq)
}

void GetCurrentSequenceReq::SharedCtor() {
  id_ = 0u;
  _cached_size_ = 0;
}

GetCurrentSequenceReq::~GetCurrentSequenceReq() {
  // @@protoc_insertion_point(destructor:zproto.GetCurrentSequenceReq)
  SharedDtor();
}

void GetCurrentSequenceReq::SharedDtor() {
}

void GetCurrentSequenceReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetCurrentSequenceReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetCurrentSequenceReq_descriptor_;
}

const GetCurrentSequenceReq& GetCurrentSequenceReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<GetCurrentSequenceReq> GetCurrentSequenceReq_default_instance_;

GetCurrentSequenceReq* GetCurrentSequenceReq::New(::google::protobuf::Arena* arena) const {
  GetCurrentSequenceReq* n = new GetCurrentSequenceReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetCurrentSequenceReq::UnsafeMergeFrom(const GetCurrentSequenceReq& from) {
  MergeFrom(from);
}
void GetCurrentSequenceReq::Swap(GetCurrentSequenceReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetCurrentSequenceReq::InternalSwap(GetCurrentSequenceReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetCurrentSequenceReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetCurrentSequenceReq_descriptor_;
  metadata.reflection = GetCurrentSequenceReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetCurrentSequenceReq

// optional uint32 id = 1;
void GetCurrentSequenceReq::clear_id() {
  id_ = 0u;
}
::google::protobuf::uint32 GetCurrentSequenceReq::id() const {
  // @@protoc_insertion_point(field_get:zproto.GetCurrentSequenceReq.id)
  return id_;
}
void GetCurrentSequenceReq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.GetCurrentSequenceReq.id)
}

inline const GetCurrentSequenceReq* GetCurrentSequenceReq::internal_default_instance() {
  return &GetCurrentSequenceReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SequenceRsp::kSequenceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SequenceRsp::SequenceRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SequenceRsp)
}

void SequenceRsp::InitAsDefaultInstance() {
}

SequenceRsp::SequenceRsp(const SequenceRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SequenceRsp)
}

void SequenceRsp::SharedCtor() {
  sequence_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

SequenceRsp::~SequenceRsp() {
  // @@protoc_insertion_point(destructor:zproto.SequenceRsp)
  SharedDtor();
}

void SequenceRsp::SharedDtor() {
}

void SequenceRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SequenceRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SequenceRsp_descriptor_;
}

const SequenceRsp& SequenceRsp::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SequenceRsp> SequenceRsp_default_instance_;

SequenceRsp* SequenceRsp::New(::google::protobuf::Arena* arena) const {
  SequenceRsp* n = new SequenceRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SequenceRsp::UnsafeMergeFrom(const SequenceRsp& from) {
  MergeFrom(from);
}
void SequenceRsp::Swap(SequenceRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SequenceRsp::InternalSwap(SequenceRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SequenceRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SequenceRsp_descriptor_;
  metadata.reflection = SequenceRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SequenceRsp

// optional uint64 sequence = 1;
void SequenceRsp::clear_sequence() {
  sequence_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SequenceRsp::sequence() const {
  // @@protoc_insertion_point(field_get:zproto.SequenceRsp.sequence)
  return sequence_;
}
void SequenceRsp::set_sequence(::google::protobuf::uint64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:zproto.SequenceRsp.sequence)
}

inline const SequenceRsp* SequenceRsp::internal_default_instance() {
  return &SequenceRsp_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FetchNextSequenceListReq::kIdListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FetchNextSequenceListReq::FetchNextSequenceListReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.FetchNextSequenceListReq)
}

void FetchNextSequenceListReq::InitAsDefaultInstance() {
}

FetchNextSequenceListReq::FetchNextSequenceListReq(const FetchNextSequenceListReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.FetchNextSequenceListReq)
}

void FetchNextSequenceListReq::SharedCtor() {
  _cached_size_ = 0;
}

FetchNextSequenceListReq::~FetchNextSequenceListReq() {
  // @@protoc_insertion_point(destructor:zproto.FetchNextSequenceListReq)
  SharedDtor();
}

void FetchNextSequenceListReq::SharedDtor() {
}

void FetchNextSequenceListReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FetchNextSequenceListReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FetchNextSequenceListReq_descriptor_;
}

const FetchNextSequenceListReq& FetchNextSequenceListReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<FetchNextSequenceListReq> FetchNextSequenceListReq_default_instance_;

FetchNextSequenceListReq* FetchNextSequenceListReq::New(::google::protobuf::Arena* arena) const {
  FetchNextSequenceListReq* n = new FetchNextSequenceListReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FetchNextSequenceListReq::UnsafeMergeFrom(const FetchNextSequenceListReq& from) {
  MergeFrom(from);
}
void FetchNextSequenceListReq::Swap(FetchNextSequenceListReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FetchNextSequenceListReq::InternalSwap(FetchNextSequenceListReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata FetchNextSequenceListReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FetchNextSequenceListReq_descriptor_;
  metadata.reflection = FetchNextSequenceListReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FetchNextSequenceListReq

// repeated uint32 id_list = 1;
int FetchNextSequenceListReq::id_list_size() const {
  return id_list_.size();
}
void FetchNextSequenceListReq::clear_id_list() {
  id_list_.Clear();
}
::google::protobuf::uint32 FetchNextSequenceListReq::id_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.FetchNextSequenceListReq.id_list)
  return id_list_.Get(index);
}
void FetchNextSequenceListReq::set_id_list(int index, ::google::protobuf::uint32 value) {
  id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.FetchNextSequenceListReq.id_list)
}
void FetchNextSequenceListReq::add_id_list(::google::protobuf::uint32 value) {
  id_list_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.FetchNextSequenceListReq.id_list)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
FetchNextSequenceListReq::id_list() const {
  // @@protoc_insertion_point(field_list:zproto.FetchNextSequenceListReq.id_list)
  return id_list_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
FetchNextSequenceListReq::mutable_id_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.FetchNextSequenceListReq.id_list)
  return &id_list_;
}

inline const FetchNextSequenceListReq* FetchNextSequenceListReq::internal_default_instance() {
  return &FetchNextSequenceListReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetCurrentSequenceListReq::kIdListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetCurrentSequenceListReq::GetCurrentSequenceListReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetCurrentSequenceListReq)
}

void GetCurrentSequenceListReq::InitAsDefaultInstance() {
}

GetCurrentSequenceListReq::GetCurrentSequenceListReq(const GetCurrentSequenceListReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetCurrentSequenceListReq)
}

void GetCurrentSequenceListReq::SharedCtor() {
  _cached_size_ = 0;
}

GetCurrentSequenceListReq::~GetCurrentSequenceListReq() {
  // @@protoc_insertion_point(destructor:zproto.GetCurrentSequenceListReq)
  SharedDtor();
}

void GetCurrentSequenceListReq::SharedDtor() {
}

void GetCurrentSequenceListReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetCurrentSequenceListReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetCurrentSequenceListReq_descriptor_;
}

const GetCurrentSequenceListReq& GetCurrentSequenceListReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<GetCurrentSequenceListReq> GetCurrentSequenceListReq_default_instance_;

GetCurrentSequenceListReq* GetCurrentSequenceListReq::New(::google::protobuf::Arena* arena) const {
  GetCurrentSequenceListReq* n = new GetCurrentSequenceListReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetCurrentSequenceListReq::UnsafeMergeFrom(const GetCurrentSequenceListReq& from) {
  MergeFrom(from);
}
void GetCurrentSequenceListReq::Swap(GetCurrentSequenceListReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetCurrentSequenceListReq::InternalSwap(GetCurrentSequenceListReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetCurrentSequenceListReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetCurrentSequenceListReq_descriptor_;
  metadata.reflection = GetCurrentSequenceListReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetCurrentSequenceListReq

// repeated uint32 id_list = 1;
int GetCurrentSequenceListReq::id_list_size() const {
  return id_list_.size();
}
void GetCurrentSequenceListReq::clear_id_list() {
  id_list_.Clear();
}
::google::protobuf::uint32 GetCurrentSequenceListReq::id_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetCurrentSequenceListReq.id_list)
  return id_list_.Get(index);
}
void GetCurrentSequenceListReq::set_id_list(int index, ::google::protobuf::uint32 value) {
  id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.GetCurrentSequenceListReq.id_list)
}
void GetCurrentSequenceListReq::add_id_list(::google::protobuf::uint32 value) {
  id_list_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.GetCurrentSequenceListReq.id_list)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GetCurrentSequenceListReq::id_list() const {
  // @@protoc_insertion_point(field_list:zproto.GetCurrentSequenceListReq.id_list)
  return id_list_;
}
::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GetCurrentSequenceListReq::mutable_id_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetCurrentSequenceListReq.id_list)
  return &id_list_;
}

inline const GetCurrentSequenceListReq* GetCurrentSequenceListReq::internal_default_instance() {
  return &GetCurrentSequenceListReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IdSeq::kIdFieldNumber;
const int IdSeq::kSequenceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IdSeq::IdSeq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.IdSeq)
}

void IdSeq::InitAsDefaultInstance() {
}

IdSeq::IdSeq(const IdSeq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.IdSeq)
}

void IdSeq::SharedCtor() {
  ::memset(&sequence_, 0, reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&sequence_) + sizeof(id_));
  _cached_size_ = 0;
}

IdSeq::~IdSeq() {
  // @@protoc_insertion_point(destructor:zproto.IdSeq)
  SharedDtor();
}

void IdSeq::SharedDtor() {
}

void IdSeq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* IdSeq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return IdSeq_descriptor_;
}

const IdSeq& IdSeq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<IdSeq> IdSeq_default_instance_;

IdSeq* IdSeq::New(::google::protobuf::Arena* arena) const {
  IdSeq* n = new IdSeq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void IdSeq::UnsafeMergeFrom(const IdSeq& from) {
  MergeFrom(from);
}
void IdSeq::Swap(IdSeq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IdSeq::InternalSwap(IdSeq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata IdSeq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = IdSeq_descriptor_;
  metadata.reflection = IdSeq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// IdSeq

// optional uint32 id = 1;
void IdSeq::clear_id() {
  id_ = 0u;
}
::google::protobuf::uint32 IdSeq::id() const {
  // @@protoc_insertion_point(field_get:zproto.IdSeq.id)
  return id_;
}
void IdSeq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.IdSeq.id)
}

// optional uint64 sequence = 2;
void IdSeq::clear_sequence() {
  sequence_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 IdSeq::sequence() const {
  // @@protoc_insertion_point(field_get:zproto.IdSeq.sequence)
  return sequence_;
}
void IdSeq::set_sequence(::google::protobuf::uint64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:zproto.IdSeq.sequence)
}

inline const IdSeq* IdSeq::internal_default_instance() {
  return &IdSeq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SequenceListRsp::kSequenceListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SequenceListRsp::SequenceListRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SequenceListRsp)
}

void SequenceListRsp::InitAsDefaultInstance() {
}

SequenceListRsp::SequenceListRsp(const SequenceListRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SequenceListRsp)
}

void SequenceListRsp::SharedCtor() {
  _cached_size_ = 0;
}

SequenceListRsp::~SequenceListRsp() {
  // @@protoc_insertion_point(destructor:zproto.SequenceListRsp)
  SharedDtor();
}

void SequenceListRsp::SharedDtor() {
}

void SequenceListRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SequenceListRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SequenceListRsp_descriptor_;
}

const SequenceListRsp& SequenceListRsp::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SequenceListRsp> SequenceListRsp_default_instance_;

SequenceListRsp* SequenceListRsp::New(::google::protobuf::Arena* arena) const {
  SequenceListRsp* n = new SequenceListRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SequenceListRsp::UnsafeMergeFrom(const SequenceListRsp& from) {
  MergeFrom(from);
}
void SequenceListRsp::Swap(SequenceListRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SequenceListRsp::InternalSwap(SequenceListRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SequenceListRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SequenceListRsp_descriptor_;
  metadata.reflection = SequenceListRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SequenceListRsp

// repeated .zproto.IdSeq sequence_list = 1;
int SequenceListRsp::sequence_list_size() const {
  return sequence_list_.size();
}
void SequenceListRsp::clear_sequence_list() {
  sequence_list_.Clear();
}
const ::zproto::IdSeq& SequenceListRsp::sequence_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Get(index);
}
::zproto::IdSeq* SequenceListRsp::mutable_sequence_list(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Mutable(index);
}
::zproto::IdSeq* SequenceListRsp::add_sequence_list() {
  // @@protoc_insertion_point(field_add:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >*
SequenceListRsp::mutable_sequence_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SequenceListRsp.sequence_list)
  return &sequence_list_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >&
SequenceListRsp::sequence_list() const {
  // @@protoc_insertion_point(field_list:zproto.SequenceListRsp.sequence_list)
  return sequence_list_;
}

inline const SequenceListRsp* SequenceListRsp::internal_default_instance() {
  return &SequenceListRsp_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoadMaxSeqsDataReq::kSetIdFieldNumber;
const int LoadMaxSeqsDataReq::kAllocIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoadMaxSeqsDataReq::LoadMaxSeqsDataReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.LoadMaxSeqsDataReq)
}

void LoadMaxSeqsDataReq::InitAsDefaultInstance() {
}

LoadMaxSeqsDataReq::LoadMaxSeqsDataReq(const LoadMaxSeqsDataReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.LoadMaxSeqsDataReq)
}

void LoadMaxSeqsDataReq::SharedCtor() {
  ::memset(&set_id_, 0, reinterpret_cast<char*>(&alloc_id_) -
    reinterpret_cast<char*>(&set_id_) + sizeof(alloc_id_));
  _cached_size_ = 0;
}

LoadMaxSeqsDataReq::~LoadMaxSeqsDataReq() {
  // @@protoc_insertion_point(destructor:zproto.LoadMaxSeqsDataReq)
  SharedDtor();
}

void LoadMaxSeqsDataReq::SharedDtor() {
}

void LoadMaxSeqsDataReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadMaxSeqsDataReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadMaxSeqsDataReq_descriptor_;
}

const LoadMaxSeqsDataReq& LoadMaxSeqsDataReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<LoadMaxSeqsDataReq> LoadMaxSeqsDataReq_default_instance_;

LoadMaxSeqsDataReq* LoadMaxSeqsDataReq::New(::google::protobuf::Arena* arena) const {
  LoadMaxSeqsDataReq* n = new LoadMaxSeqsDataReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoadMaxSeqsDataReq::UnsafeMergeFrom(const LoadMaxSeqsDataReq& from) {
  MergeFrom(from);
}
void LoadMaxSeqsDataReq::Swap(LoadMaxSeqsDataReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoadMaxSeqsDataReq::InternalSwap(LoadMaxSeqsDataReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata LoadMaxSeqsDataReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoadMaxSeqsDataReq_descriptor_;
  metadata.reflection = LoadMaxSeqsDataReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadMaxSeqsDataReq

// optional uint32 set_id = 1;
void LoadMaxSeqsDataReq::clear_set_id() {
  set_id_ = 0u;
}
::google::protobuf::uint32 LoadMaxSeqsDataReq::set_id() const {
  // @@protoc_insertion_point(field_get:zproto.LoadMaxSeqsDataReq.set_id)
  return set_id_;
}
void LoadMaxSeqsDataReq::set_set_id(::google::protobuf::uint32 value) {
  
  set_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.LoadMaxSeqsDataReq.set_id)
}

// optional uint32 alloc_id = 2;
void LoadMaxSeqsDataReq::clear_alloc_id() {
  alloc_id_ = 0u;
}
::google::protobuf::uint32 LoadMaxSeqsDataReq::alloc_id() const {
  // @@protoc_insertion_point(field_get:zproto.LoadMaxSeqsDataReq.alloc_id)
  return alloc_id_;
}
void LoadMaxSeqsDataReq::set_alloc_id(::google::protobuf::uint32 value) {
  
  alloc_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.LoadMaxSeqsDataReq.alloc_id)
}

inline const LoadMaxSeqsDataReq* LoadMaxSeqsDataReq::internal_default_instance() {
  return &LoadMaxSeqsDataReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoadMaxSeqsDataRsp::kMaxSeqsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoadMaxSeqsDataRsp::LoadMaxSeqsDataRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.LoadMaxSeqsDataRsp)
}

void LoadMaxSeqsDataRsp::InitAsDefaultInstance() {
}

LoadMaxSeqsDataRsp::LoadMaxSeqsDataRsp(const LoadMaxSeqsDataRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.LoadMaxSeqsDataRsp)
}

void LoadMaxSeqsDataRsp::SharedCtor() {
  max_seqs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

LoadMaxSeqsDataRsp::~LoadMaxSeqsDataRsp() {
  // @@protoc_insertion_point(destructor:zproto.LoadMaxSeqsDataRsp)
  SharedDtor();
}

void LoadMaxSeqsDataRsp::SharedDtor() {
  max_seqs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoadMaxSeqsDataRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadMaxSeqsDataRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadMaxSeqsDataRsp_descriptor_;
}

const LoadMaxSeqsDataRsp& LoadMaxSeqsDataRsp::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<LoadMaxSeqsDataRsp> LoadMaxSeqsDataRsp_default_instance_;

LoadMaxSeqsDataRsp* LoadMaxSeqsDataRsp::New(::google::protobuf::Arena* arena) const {
  LoadMaxSeqsDataRsp* n = new LoadMaxSeqsDataRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoadMaxSeqsDataRsp::UnsafeMergeFrom(const LoadMaxSeqsDataRsp& from) {
  MergeFrom(from);
}
void LoadMaxSeqsDataRsp::Swap(LoadMaxSeqsDataRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoadMaxSeqsDataRsp::InternalSwap(LoadMaxSeqsDataRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata LoadMaxSeqsDataRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoadMaxSeqsDataRsp_descriptor_;
  metadata.reflection = LoadMaxSeqsDataRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadMaxSeqsDataRsp

// optional bytes max_seqs = 1;
void LoadMaxSeqsDataRsp::clear_max_seqs() {
  max_seqs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoadMaxSeqsDataRsp::max_seqs() const {
  // @@protoc_insertion_point(field_get:zproto.LoadMaxSeqsDataRsp.max_seqs)
  return max_seqs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoadMaxSeqsDataRsp::set_max_seqs(const ::std::string& value) {
  
  max_seqs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.LoadMaxSeqsDataRsp.max_seqs)
}
void LoadMaxSeqsDataRsp::set_max_seqs(const char* value) {
  
  max_seqs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.LoadMaxSeqsDataRsp.max_seqs)
}
void LoadMaxSeqsDataRsp::set_max_seqs(const void* value, size_t size) {
  
  max_seqs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.LoadMaxSeqsDataRsp.max_seqs)
}
::std::string* LoadMaxSeqsDataRsp::mutable_max_seqs() {
  
  // @@protoc_insertion_point(field_mutable:zproto.LoadMaxSeqsDataRsp.max_seqs)
  return max_seqs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoadMaxSeqsDataRsp::release_max_seqs() {
  // @@protoc_insertion_point(field_release:zproto.LoadMaxSeqsDataRsp.max_seqs)
  
  return max_seqs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoadMaxSeqsDataRsp::set_allocated_max_seqs(::std::string* max_seqs) {
  if (max_seqs != NULL) {
    
  } else {
    
  }
  max_seqs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), max_seqs);
  // @@protoc_insertion_point(field_set_allocated:zproto.LoadMaxSeqsDataRsp.max_seqs)
}

inline const LoadMaxSeqsDataRsp* LoadMaxSeqsDataRsp::internal_default_instance() {
  return &LoadMaxSeqsDataRsp_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SaveMaxSeqReq::kSetIdFieldNumber;
const int SaveMaxSeqReq::kAllocIdFieldNumber;
const int SaveMaxSeqReq::kSectionIdFieldNumber;
const int SaveMaxSeqReq::kMaxSeqFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SaveMaxSeqReq::SaveMaxSeqReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SaveMaxSeqReq)
}

void SaveMaxSeqReq::InitAsDefaultInstance() {
}

SaveMaxSeqReq::SaveMaxSeqReq(const SaveMaxSeqReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SaveMaxSeqReq)
}

void SaveMaxSeqReq::SharedCtor() {
  ::memset(&set_id_, 0, reinterpret_cast<char*>(&section_id_) -
    reinterpret_cast<char*>(&set_id_) + sizeof(section_id_));
  _cached_size_ = 0;
}

SaveMaxSeqReq::~SaveMaxSeqReq() {
  // @@protoc_insertion_point(destructor:zproto.SaveMaxSeqReq)
  SharedDtor();
}

void SaveMaxSeqReq::SharedDtor() {
}

void SaveMaxSeqReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SaveMaxSeqReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SaveMaxSeqReq_descriptor_;
}

const SaveMaxSeqReq& SaveMaxSeqReq::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SaveMaxSeqReq> SaveMaxSeqReq_default_instance_;

SaveMaxSeqReq* SaveMaxSeqReq::New(::google::protobuf::Arena* arena) const {
  SaveMaxSeqReq* n = new SaveMaxSeqReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SaveMaxSeqReq::UnsafeMergeFrom(const SaveMaxSeqReq& from) {
  MergeFrom(from);
}
void SaveMaxSeqReq::Swap(SaveMaxSeqReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SaveMaxSeqReq::InternalSwap(SaveMaxSeqReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SaveMaxSeqReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SaveMaxSeqReq_descriptor_;
  metadata.reflection = SaveMaxSeqReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SaveMaxSeqReq

// optional uint32 set_id = 1;
void SaveMaxSeqReq::clear_set_id() {
  set_id_ = 0u;
}
::google::protobuf::uint32 SaveMaxSeqReq::set_id() const {
  // @@protoc_insertion_point(field_get:zproto.SaveMaxSeqReq.set_id)
  return set_id_;
}
void SaveMaxSeqReq::set_set_id(::google::protobuf::uint32 value) {
  
  set_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.SaveMaxSeqReq.set_id)
}

// optional uint32 alloc_id = 2;
void SaveMaxSeqReq::clear_alloc_id() {
  alloc_id_ = 0u;
}
::google::protobuf::uint32 SaveMaxSeqReq::alloc_id() const {
  // @@protoc_insertion_point(field_get:zproto.SaveMaxSeqReq.alloc_id)
  return alloc_id_;
}
void SaveMaxSeqReq::set_alloc_id(::google::protobuf::uint32 value) {
  
  alloc_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.SaveMaxSeqReq.alloc_id)
}

// optional uint32 section_id = 3;
void SaveMaxSeqReq::clear_section_id() {
  section_id_ = 0u;
}
::google::protobuf::uint32 SaveMaxSeqReq::section_id() const {
  // @@protoc_insertion_point(field_get:zproto.SaveMaxSeqReq.section_id)
  return section_id_;
}
void SaveMaxSeqReq::set_section_id(::google::protobuf::uint32 value) {
  
  section_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.SaveMaxSeqReq.section_id)
}

// optional uint64 max_seq = 4;
void SaveMaxSeqReq::clear_max_seq() {
  max_seq_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SaveMaxSeqReq::max_seq() const {
  // @@protoc_insertion_point(field_get:zproto.SaveMaxSeqReq.max_seq)
  return max_seq_;
}
void SaveMaxSeqReq::set_max_seq(::google::protobuf::uint64 value) {
  
  max_seq_ = value;
  // @@protoc_insertion_point(field_set:zproto.SaveMaxSeqReq.max_seq)
}

inline const SaveMaxSeqReq* SaveMaxSeqReq::internal_default_instance() {
  return &SaveMaxSeqReq_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SaveMaxSeqRsp::kLastMaxSeqFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SaveMaxSeqRsp::SaveMaxSeqRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_seqsvr_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SaveMaxSeqRsp)
}

void SaveMaxSeqRsp::InitAsDefaultInstance() {
}

SaveMaxSeqRsp::SaveMaxSeqRsp(const SaveMaxSeqRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SaveMaxSeqRsp)
}

void SaveMaxSeqRsp::SharedCtor() {
  last_max_seq_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

SaveMaxSeqRsp::~SaveMaxSeqRsp() {
  // @@protoc_insertion_point(destructor:zproto.SaveMaxSeqRsp)
  SharedDtor();
}

void SaveMaxSeqRsp::SharedDtor() {
}

void SaveMaxSeqRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SaveMaxSeqRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SaveMaxSeqRsp_descriptor_;
}

const SaveMaxSeqRsp& SaveMaxSeqRsp::default_instance() {
  protobuf_InitDefaults_seqsvr_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<SaveMaxSeqRsp> SaveMaxSeqRsp_default_instance_;

SaveMaxSeqRsp* SaveMaxSeqRsp::New(::google::protobuf::Arena* arena) const {
  SaveMaxSeqRsp* n = new SaveMaxSeqRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SaveMaxSeqRsp::UnsafeMergeFrom(const SaveMaxSeqRsp& from) {
  MergeFrom(from);
}
void SaveMaxSeqRsp::Swap(SaveMaxSeqRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SaveMaxSeqRsp::InternalSwap(SaveMaxSeqRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SaveMaxSeqRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SaveMaxSeqRsp_descriptor_;
  metadata.reflection = SaveMaxSeqRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SaveMaxSeqRsp

// optional uint64 last_max_seq = 1;
void SaveMaxSeqRsp::clear_last_max_seq() {
  last_max_seq_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SaveMaxSeqRsp::last_max_seq() const {
  // @@protoc_insertion_point(field_get:zproto.SaveMaxSeqRsp.last_max_seq)
  return last_max_seq_;
}
void SaveMaxSeqRsp::set_last_max_seq(::google::protobuf::uint64 value) {
  
  last_max_seq_ = value;
  // @@protoc_insertion_point(field_set:zproto.SaveMaxSeqRsp.last_max_seq)
}

inline const SaveMaxSeqRsp* SaveMaxSeqRsp::internal_default_instance() {
  return &SaveMaxSeqRsp_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
