// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seqsvr.proto

#ifndef PROTOBUF_seqsvr_2eproto__INCLUDED
#define PROTOBUF_seqsvr_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace zproto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_seqsvr_2eproto();
void protobuf_InitDefaults_seqsvr_2eproto();
void protobuf_AssignDesc_seqsvr_2eproto();
void protobuf_ShutdownFile_seqsvr_2eproto();

class FetchNextSequenceListReq;
class FetchNextSequenceReq;
class GetCurrentSequenceListReq;
class GetCurrentSequenceReq;
class IdSeq;
class SequenceListRsp;
class SequenceRsp;

// ===================================================================

class FetchNextSequenceReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.FetchNextSequenceReq) */ {
 public:
  FetchNextSequenceReq();
  virtual ~FetchNextSequenceReq();

  FetchNextSequenceReq(const FetchNextSequenceReq& from);

  inline FetchNextSequenceReq& operator=(const FetchNextSequenceReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FetchNextSequenceReq& default_instance();

  static const FetchNextSequenceReq* internal_default_instance();

  void Swap(FetchNextSequenceReq* other);

  // implements Message ----------------------------------------------

  inline FetchNextSequenceReq* New() const { return New(NULL); }

  FetchNextSequenceReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FetchNextSequenceReq* other);
  void UnsafeMergeFrom(const FetchNextSequenceReq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zproto.FetchNextSequenceReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<FetchNextSequenceReq> FetchNextSequenceReq_default_instance_;

// -------------------------------------------------------------------

class GetCurrentSequenceReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.GetCurrentSequenceReq) */ {
 public:
  GetCurrentSequenceReq();
  virtual ~GetCurrentSequenceReq();

  GetCurrentSequenceReq(const GetCurrentSequenceReq& from);

  inline GetCurrentSequenceReq& operator=(const GetCurrentSequenceReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetCurrentSequenceReq& default_instance();

  static const GetCurrentSequenceReq* internal_default_instance();

  void Swap(GetCurrentSequenceReq* other);

  // implements Message ----------------------------------------------

  inline GetCurrentSequenceReq* New() const { return New(NULL); }

  GetCurrentSequenceReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetCurrentSequenceReq* other);
  void UnsafeMergeFrom(const GetCurrentSequenceReq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zproto.GetCurrentSequenceReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetCurrentSequenceReq> GetCurrentSequenceReq_default_instance_;

// -------------------------------------------------------------------

class SequenceRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.SequenceRsp) */ {
 public:
  SequenceRsp();
  virtual ~SequenceRsp();

  SequenceRsp(const SequenceRsp& from);

  inline SequenceRsp& operator=(const SequenceRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SequenceRsp& default_instance();

  static const SequenceRsp* internal_default_instance();

  void Swap(SequenceRsp* other);

  // implements Message ----------------------------------------------

  inline SequenceRsp* New() const { return New(NULL); }

  SequenceRsp* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SequenceRsp* other);
  void UnsafeMergeFrom(const SequenceRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 sequence = 1;
  void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  ::google::protobuf::uint64 sequence() const;
  void set_sequence(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zproto.SequenceRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 sequence_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SequenceRsp> SequenceRsp_default_instance_;

// -------------------------------------------------------------------

class FetchNextSequenceListReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.FetchNextSequenceListReq) */ {
 public:
  FetchNextSequenceListReq();
  virtual ~FetchNextSequenceListReq();

  FetchNextSequenceListReq(const FetchNextSequenceListReq& from);

  inline FetchNextSequenceListReq& operator=(const FetchNextSequenceListReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FetchNextSequenceListReq& default_instance();

  static const FetchNextSequenceListReq* internal_default_instance();

  void Swap(FetchNextSequenceListReq* other);

  // implements Message ----------------------------------------------

  inline FetchNextSequenceListReq* New() const { return New(NULL); }

  FetchNextSequenceListReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FetchNextSequenceListReq* other);
  void UnsafeMergeFrom(const FetchNextSequenceListReq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 id_list = 1;
  int id_list_size() const;
  void clear_id_list();
  static const int kIdListFieldNumber = 1;
  ::google::protobuf::uint32 id_list(int index) const;
  void set_id_list(int index, ::google::protobuf::uint32 value);
  void add_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_id_list();

  // @@protoc_insertion_point(class_scope:zproto.FetchNextSequenceListReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > id_list_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<FetchNextSequenceListReq> FetchNextSequenceListReq_default_instance_;

// -------------------------------------------------------------------

class GetCurrentSequenceListReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.GetCurrentSequenceListReq) */ {
 public:
  GetCurrentSequenceListReq();
  virtual ~GetCurrentSequenceListReq();

  GetCurrentSequenceListReq(const GetCurrentSequenceListReq& from);

  inline GetCurrentSequenceListReq& operator=(const GetCurrentSequenceListReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetCurrentSequenceListReq& default_instance();

  static const GetCurrentSequenceListReq* internal_default_instance();

  void Swap(GetCurrentSequenceListReq* other);

  // implements Message ----------------------------------------------

  inline GetCurrentSequenceListReq* New() const { return New(NULL); }

  GetCurrentSequenceListReq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetCurrentSequenceListReq* other);
  void UnsafeMergeFrom(const GetCurrentSequenceListReq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 id_list = 1;
  int id_list_size() const;
  void clear_id_list();
  static const int kIdListFieldNumber = 1;
  ::google::protobuf::uint32 id_list(int index) const;
  void set_id_list(int index, ::google::protobuf::uint32 value);
  void add_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_id_list();

  // @@protoc_insertion_point(class_scope:zproto.GetCurrentSequenceListReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > id_list_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<GetCurrentSequenceListReq> GetCurrentSequenceListReq_default_instance_;

// -------------------------------------------------------------------

class IdSeq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.IdSeq) */ {
 public:
  IdSeq();
  virtual ~IdSeq();

  IdSeq(const IdSeq& from);

  inline IdSeq& operator=(const IdSeq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IdSeq& default_instance();

  static const IdSeq* internal_default_instance();

  void Swap(IdSeq* other);

  // implements Message ----------------------------------------------

  inline IdSeq* New() const { return New(NULL); }

  IdSeq* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IdSeq* other);
  void UnsafeMergeFrom(const IdSeq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint64 sequence = 2;
  void clear_sequence();
  static const int kSequenceFieldNumber = 2;
  ::google::protobuf::uint64 sequence() const;
  void set_sequence(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zproto.IdSeq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 sequence_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<IdSeq> IdSeq_default_instance_;

// -------------------------------------------------------------------

class SequenceListRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.SequenceListRsp) */ {
 public:
  SequenceListRsp();
  virtual ~SequenceListRsp();

  SequenceListRsp(const SequenceListRsp& from);

  inline SequenceListRsp& operator=(const SequenceListRsp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SequenceListRsp& default_instance();

  static const SequenceListRsp* internal_default_instance();

  void Swap(SequenceListRsp* other);

  // implements Message ----------------------------------------------

  inline SequenceListRsp* New() const { return New(NULL); }

  SequenceListRsp* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SequenceListRsp* other);
  void UnsafeMergeFrom(const SequenceListRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .zproto.IdSeq sequence_list = 1;
  int sequence_list_size() const;
  void clear_sequence_list();
  static const int kSequenceListFieldNumber = 1;
  const ::zproto::IdSeq& sequence_list(int index) const;
  ::zproto::IdSeq* mutable_sequence_list(int index);
  ::zproto::IdSeq* add_sequence_list();
  ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >*
      mutable_sequence_list();
  const ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >&
      sequence_list() const;

  // @@protoc_insertion_point(class_scope:zproto.SequenceListRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq > sequence_list_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_seqsvr_2eproto_impl();
  friend void  protobuf_AddDesc_seqsvr_2eproto_impl();
  friend void protobuf_AssignDesc_seqsvr_2eproto();
  friend void protobuf_ShutdownFile_seqsvr_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SequenceListRsp> SequenceListRsp_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// FetchNextSequenceReq

// optional uint32 id = 1;
inline void FetchNextSequenceReq::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 FetchNextSequenceReq::id() const {
  // @@protoc_insertion_point(field_get:zproto.FetchNextSequenceReq.id)
  return id_;
}
inline void FetchNextSequenceReq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.FetchNextSequenceReq.id)
}

inline const FetchNextSequenceReq* FetchNextSequenceReq::internal_default_instance() {
  return &FetchNextSequenceReq_default_instance_.get();
}
// -------------------------------------------------------------------

// GetCurrentSequenceReq

// optional uint32 id = 1;
inline void GetCurrentSequenceReq::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 GetCurrentSequenceReq::id() const {
  // @@protoc_insertion_point(field_get:zproto.GetCurrentSequenceReq.id)
  return id_;
}
inline void GetCurrentSequenceReq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.GetCurrentSequenceReq.id)
}

inline const GetCurrentSequenceReq* GetCurrentSequenceReq::internal_default_instance() {
  return &GetCurrentSequenceReq_default_instance_.get();
}
// -------------------------------------------------------------------

// SequenceRsp

// optional uint64 sequence = 1;
inline void SequenceRsp::clear_sequence() {
  sequence_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SequenceRsp::sequence() const {
  // @@protoc_insertion_point(field_get:zproto.SequenceRsp.sequence)
  return sequence_;
}
inline void SequenceRsp::set_sequence(::google::protobuf::uint64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:zproto.SequenceRsp.sequence)
}

inline const SequenceRsp* SequenceRsp::internal_default_instance() {
  return &SequenceRsp_default_instance_.get();
}
// -------------------------------------------------------------------

// FetchNextSequenceListReq

// repeated uint32 id_list = 1;
inline int FetchNextSequenceListReq::id_list_size() const {
  return id_list_.size();
}
inline void FetchNextSequenceListReq::clear_id_list() {
  id_list_.Clear();
}
inline ::google::protobuf::uint32 FetchNextSequenceListReq::id_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.FetchNextSequenceListReq.id_list)
  return id_list_.Get(index);
}
inline void FetchNextSequenceListReq::set_id_list(int index, ::google::protobuf::uint32 value) {
  id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.FetchNextSequenceListReq.id_list)
}
inline void FetchNextSequenceListReq::add_id_list(::google::protobuf::uint32 value) {
  id_list_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.FetchNextSequenceListReq.id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
FetchNextSequenceListReq::id_list() const {
  // @@protoc_insertion_point(field_list:zproto.FetchNextSequenceListReq.id_list)
  return id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
FetchNextSequenceListReq::mutable_id_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.FetchNextSequenceListReq.id_list)
  return &id_list_;
}

inline const FetchNextSequenceListReq* FetchNextSequenceListReq::internal_default_instance() {
  return &FetchNextSequenceListReq_default_instance_.get();
}
// -------------------------------------------------------------------

// GetCurrentSequenceListReq

// repeated uint32 id_list = 1;
inline int GetCurrentSequenceListReq::id_list_size() const {
  return id_list_.size();
}
inline void GetCurrentSequenceListReq::clear_id_list() {
  id_list_.Clear();
}
inline ::google::protobuf::uint32 GetCurrentSequenceListReq::id_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetCurrentSequenceListReq.id_list)
  return id_list_.Get(index);
}
inline void GetCurrentSequenceListReq::set_id_list(int index, ::google::protobuf::uint32 value) {
  id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.GetCurrentSequenceListReq.id_list)
}
inline void GetCurrentSequenceListReq::add_id_list(::google::protobuf::uint32 value) {
  id_list_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.GetCurrentSequenceListReq.id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GetCurrentSequenceListReq::id_list() const {
  // @@protoc_insertion_point(field_list:zproto.GetCurrentSequenceListReq.id_list)
  return id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GetCurrentSequenceListReq::mutable_id_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetCurrentSequenceListReq.id_list)
  return &id_list_;
}

inline const GetCurrentSequenceListReq* GetCurrentSequenceListReq::internal_default_instance() {
  return &GetCurrentSequenceListReq_default_instance_.get();
}
// -------------------------------------------------------------------

// IdSeq

// optional uint32 id = 1;
inline void IdSeq::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 IdSeq::id() const {
  // @@protoc_insertion_point(field_get:zproto.IdSeq.id)
  return id_;
}
inline void IdSeq::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:zproto.IdSeq.id)
}

// optional uint64 sequence = 2;
inline void IdSeq::clear_sequence() {
  sequence_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 IdSeq::sequence() const {
  // @@protoc_insertion_point(field_get:zproto.IdSeq.sequence)
  return sequence_;
}
inline void IdSeq::set_sequence(::google::protobuf::uint64 value) {
  
  sequence_ = value;
  // @@protoc_insertion_point(field_set:zproto.IdSeq.sequence)
}

inline const IdSeq* IdSeq::internal_default_instance() {
  return &IdSeq_default_instance_.get();
}
// -------------------------------------------------------------------

// SequenceListRsp

// repeated .zproto.IdSeq sequence_list = 1;
inline int SequenceListRsp::sequence_list_size() const {
  return sequence_list_.size();
}
inline void SequenceListRsp::clear_sequence_list() {
  sequence_list_.Clear();
}
inline const ::zproto::IdSeq& SequenceListRsp::sequence_list(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Get(index);
}
inline ::zproto::IdSeq* SequenceListRsp::mutable_sequence_list(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Mutable(index);
}
inline ::zproto::IdSeq* SequenceListRsp::add_sequence_list() {
  // @@protoc_insertion_point(field_add:zproto.SequenceListRsp.sequence_list)
  return sequence_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >*
SequenceListRsp::mutable_sequence_list() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SequenceListRsp.sequence_list)
  return &sequence_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::zproto::IdSeq >&
SequenceListRsp::sequence_list() const {
  // @@protoc_insertion_point(field_list:zproto.SequenceListRsp.sequence_list)
  return sequence_list_;
}

inline const SequenceListRsp* SequenceListRsp::internal_default_instance() {
  return &SequenceListRsp_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_seqsvr_2eproto__INCLUDED
